name: Prod - build and deployment
on:
  push:
    branches:
      - 'main'

jobs:
  ReleaseExists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          if ! git branch -r --merged main | grep -q -E 'release-'; then
            echo "No branch starting with 'release-' was merged into main, as expected."
            exit 1
          fi

  BuildSimulation:
    needs: ReleaseExists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          echo Building and packing the app...
  DeploySimulation:
    runs-on: ubuntu-latest
    needs: BuildSimulation
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo Deploying the app into Production environment...